export const AuthTypes = {

    CREATE_USER_RESET: '@auth/CREATE_USER_RESET',
    CREATE_USER_REQUEST: '@auth/CREATE_USER_REQUEST',
    CREATE_USER_SUCCESS: '@auth/CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: '@auth/CREATE_USER_FAILURE',
    CHANGE_DIALOG_CREATE: '@auth/CHANGE_DIALOG_CREATE',

    LOGIN_RESET: '@auth/LOGIN_RESET',
    LOGIN_REQUEST: '@auth/LOGIN_REQUEST',
    LOGIN_SUCCESS: '@auth/LOGIN_SUCCESS',
    LOGIN_FAILURE: '@auth/LOGIN_FAILURE'
}